# host: project:region:instance
db-config:
  # docker-compose.yml sql-proxy container name
  host: "cloudsql-proxy"
  user: "root"
  name: "voda"
  port: 5432
  password: "voda1!"

client:
  kakao:
    base-url: "https://kapi.kakao.com"
    oauth:
      client-id: "c663ce96b79395b5dcc6d7f774e1af67"
      client-secret: "LLlLMwzJ9VjLXhjsJYx4pE3zsE1x9m4P"
      redirect-url: "http://localhost:8080/v1/authentication/login/kakao"
  google:
    oauth:
      client-id: "178025470998-4n07sql4vqnpsak3ggs5jg0lnk70uh0l.apps.googleusercontent.com"
      client-secret: "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"
      redirect-url: "http://localhost:8080/v1/authentication/login/google"
  apple:
    auth:
      auth-url: "https://appleid.apple.com"
      team-id: "KT2XM3Z9DZ"
      client-id: "com.catdiary.VODA.login"
      key-id: "5ND55U8SZU"
      key-path: "infrastructure/configs/apple_login_auth_key.p8"
      redirect-url: "https://exchange-diary-b4mzhzbzcq-du.a.run.app/v1/authentication/login/apple"